/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_life_client

type SubscriptionInfo struct {
	Msisdn string `json:"msisdn,omitempty"`
	Channdetails string `json:"channdetails,omitempty"`
	Transactid string `json:"transactid,omitempty"`
}
