/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger-life-client

type OffersListResponse struct {
	Status string `json:"status,omitempty"`
	Category []CategoryOffers `json:"category,omitempty"`
}
