/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger-life-client

type Subscription struct {
	Heading string `json:"heading,omitempty"`
	// short description
	Description string `json:"description,omitempty"`
	// VAS-P subscription identifier
	ServiceID string `json:"serviceID,omitempty"`
	// cost of subscription
	Cost string `json:"cost,omitempty"`
	// recurrent payment
	Pay string `json:"pay,omitempty"`
}
