/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_life_client

type CategoryOffersLabels struct {
	// label name
	Labelname string `json:"labelname,omitempty"`
	// label color code in #RRGGBB format
	Labelcolor string `json:"labelcolor,omitempty"`
}
