/*
 * Product aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_life_client

type CategoryOffers struct {
	// Category Name
	Categoryname string `json:"categoryname,omitempty"`
	// reference to the logo image
	Categorylogo string `json:"categorylogo,omitempty"`
	Offers []CategoryOffersOffers `json:"offers,omitempty"`
}
