/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
	client "github.com/moznobkin/productoffering-composite/life-client"
)

func GetInstalledBase(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetQualifiedCategories(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetQualifiedProductOfferings(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")



	w.WriteHeader(http.StatusOK)
}
func mapCategories2Qualification ([]client.CategoryOffers) (*ProductOfferingQualificationResponse, error)
{

	containers :
			
	for _, cat := 
	var p:= ProductOfferingQualificationResponse{
		ProductOfferingQualificationItemContainer: {

		}
	}
}
func getCategories () ([]client.CategoryOffers, error) {
	fs, err := os.Open("../examples/json/offerslist.json")
	if err != nil {
		panic(err)
	}
	var p []client.CategoryOffers
	err := json.NewDecoder(fs).Decode(&p)
	if err != nil {
		return nil, err
	}
	return &p, nil
}