/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Constraint reference. The Constraint resource represents a policy/rule applied to an entity or entity spec.
type ConstraintRef struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`
	// Hyperlink reference to the target constraint
	Href string `json:"href,omitempty"`
	// reference id to the target constraint
	Id string `json:"id"`
	// Name given to the constraint
	Name string `json:"name,omitempty"`
	// The (class) type of the referred constraint
	ReferredType string `json:"referredType,omitempty"`
	// constraint version
	Version string `json:"version,omitempty"`
}
