/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes a non-composite relationship between product offering prices. For example one price might be an discount alteration for another price.
type ProductOfferingPriceRelationship struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`
	// hyperlink reference of the associated product offering price
	Href string `json:"href,omitempty"`
	// Unique identifier of the associated product offering price
	Id string `json:"id"`
	// Name of the associated product offering price
	Name string `json:"name,omitempty"`
	// type of the relationship, for example override, discount, etc.
	RelationshipType string `json:"relationshipType,omitempty"`
}
