/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceabilityAddress struct {

	AdditionalLocationDetails string `json:"additionalLocationDetails,omitempty"`

	AddressId string `json:"addressId,omitempty"`

	City string `json:"city,omitempty"`

	Country string `json:"country,omitempty"`

	Housenumber string `json:"housenumber,omitempty"`

	HousenumberAddition string `json:"housenumberAddition,omitempty"`

	Postalcode string `json:"postalcode,omitempty"`

	Street string `json:"street,omitempty"`
}
