/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Place reference. PlaceRef defines the placeRefs where the products are sold or delivered.
type PlaceRef struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// The actual type of the target instance when needed for disambiguation.
	ReferredType string `json:"@referredType,omitempty"`
	//  hyperlink reference to the schema describing this resource.
	SchemaLocation string `json:"@schemaLocation,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`

	Address string `json:"address,omitempty"`
	// Reference of the related entity.
	Href string `json:"href,omitempty"`
	// Unique identifier of a related entity.
	Id string `json:"id"`
	// Name of the related entity.
	Name string `json:"name,omitempty"`
	//  Role.
	Role string `json:"role,omitempty"`
}
