/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductOrderItem struct {

	BaseType string `json:"@baseType,omitempty"`

	ReferredType string `json:"@referredType,omitempty"`

	SchemaLocation string `json:"@schemaLocation,omitempty"`

	Type_ string `json:"@type,omitempty"`

	OrderItemAction string `json:"orderItemAction,omitempty"`

	OrderItemId string `json:"orderItemId,omitempty"`

	ProductOrderHref string `json:"productOrderHref,omitempty"`

	ProductOrderId string `json:"productOrderId,omitempty"`

	Role string `json:"role,omitempty"`
}
