/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ProductOffering is made available to Customers at Offering Price level
type ProductOfferingRef struct {

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`
}
