/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductOfferingQualificationResponseProductOfferingQualificationItemContainer struct {

	Id string `json:"id,omitempty"`

	ProcessContext string `json:"processContext,omitempty"`

	QualificationItemResult string `json:"qualificationItemResult,omitempty"`

	ProductOfferingQualificationItem *ProductOfferingQualificationItem `json:"productOfferingQualificationItem,omitempty"`
}
