/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ApiErrorResponse struct {

	Errors []ModelError `json:"errors,omitempty"`
	// Api Exception Error
	Message string `json:"message,omitempty"`
	// HTTP Status
	Status string `json:"status,omitempty"`
	// Current date timestamp
	Timestamp time.Time `json:"timestamp,omitempty"`
}
