/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Source struct {
	// Actual exception occures.
	Exception string `json:"exception,omitempty"`
	// The field for which validation fails.
	Pointer string `json:"pointer,omitempty"`
}
