/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Product struct {

	BaseType string `json:"@baseType,omitempty"`

	SchemaLocation string `json:"@schemaLocation,omitempty"`

	Type_ string `json:"@type,omitempty"`

	Description string `json:"description,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	IsBundle bool `json:"isBundle,omitempty"`

	IsCustomerVisible bool `json:"isCustomerVisible,omitempty"`

	Name string `json:"name,omitempty"`

	OrderDate time.Time `json:"orderDate,omitempty"`

	Place []PlaceRef `json:"place,omitempty"`

	Product []Product `json:"product,omitempty"`

	ProductCharacteristic []Characteristic `json:"productCharacteristic,omitempty"`

	ProductLineCategory string `json:"productLineCategory,omitempty"`

	ProductOffering *ProductOfferingRef `json:"productOffering,omitempty"`

	ProductOrderItem []ProductOrderItem `json:"productOrderItem,omitempty"`

	ProductPrice []ProductPrice `json:"productPrice,omitempty"`

	ProductSerialNumber string `json:"productSerialNumber,omitempty"`

	ProductSpecification *ProductSpecification `json:"productSpecification,omitempty"`

	RelatedParty []RelatedParty `json:"relatedParty,omitempty"`

	StartDate time.Time `json:"startDate,omitempty"`

	Status string `json:"status,omitempty"`

	TerminationDate time.Time `json:"terminationDate,omitempty"`
}
