/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceabilityPackage struct {

	Availability *Availability `json:"availability,omitempty"`

	Name string `json:"name,omitempty"`

	ServiceabilityItem []ServiceabilityItem `json:"serviceabilityItem,omitempty"`

	Type_ string `json:"type,omitempty"`

	Value string `json:"value,omitempty"`
}
