/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The PricingLogicAlgorithm entity represents an instantiation of an interface specification to external rating function (without a modeled bahavior in SID). Some of the parameters of the interface definiition may be already set (such as price per unit) and some may be gathered during the rating process from the event (such as call duration) or from ProductCharacteristicValues (such as assigned bandwidth)
type PricingLogicAlgorithm struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"baseType,omitempty"`
	// Description of the PricingLogicAlgorithm
	Description string `json:"description,omitempty"`
	// hyperlink reference of this PricingLogicAlgorithm
	Href string `json:"href,omitempty"`
	// unique id of the PricingLogicAlgorithm
	Id string `json:"id"`
	// Name given to the PricingLogicAlgorithm
	Name string `json:"name,omitempty"`
	// id of corresponding PricingLogicAlgorithm specification
	PlaSpecId string `json:"plaSpecId,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"type,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
}
