/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Customer struct {

	BaseType string `json:"@baseType,omitempty"`

	SchemaLocation string `json:"@schemaLocation,omitempty"`

	Type_ string `json:"@type,omitempty"`

	Account []Account `json:"account,omitempty"`

	Agreement []AgreementRef `json:"agreement,omitempty"`

	Characteristic []Characteristic `json:"characteristic,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	RelatedParty []RelatedParty `json:"relatedParty,omitempty"`

	Status string `json:"status,omitempty"`

	StatusReason string `json:"statusReason,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
}
