/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SpecCharacteristicValue struct {
	// A string. The (immediate) base class type of this REST resource
	BaseType string `json:"@baseType,omitempty"`
	// A string class type of target specification
	Type_ string `json:"@type,omitempty"`
	// Indicates if the value is the default value for a characteristic
	IsDefault bool `json:"isDefault,omitempty"`
	// An indicator that specifies the inclusion or exclusion of the valueFrom and valueTo attributes. If applicable, possible values are \"open\", \"closed\", \"closedBottom\" and \"closedTop\".
	RangeInterval string `json:"rangeInterval,omitempty"`
	// A regular expression constraint for given value
	Regex string `json:"regex,omitempty"`
	// A length, surface, volume, dry measure, liquid measure, money, weight, time, and the like. In general, a determinate quantity or magnitude of the kind designated, taken as a standard of comparison for others of the same kind, in assigning to them numerical values, as 1 foot, 1 yard, 1 mile, 1 square foot.
	UnitOfMeasure string `json:"unitOfMeasure,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
	// A discrete value that the characteristic can take on, or the actual value of the characteristic
	Value string `json:"value,omitempty"`
	// The low range value that a characteristic can take on
	ValueFrom int32 `json:"valueFrom,omitempty"`
	// The upper range value that a characteristic can take on
	ValueTo int32 `json:"valueTo,omitempty"`
	// A kind of value that the characteristic can take on, such as numeric, text, and so forth
	ValueType string `json:"valueType,omitempty"`
}
