/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SpecCharRelationship struct {
	// A string. The (immediate) base class type of this REST resource
	BaseType string `json:"@baseType,omitempty"`
	// A string class type of target specification
	Type_ string `json:"@type,omitempty"`
	// Hyperlink reference to the target specification
	Href string `json:"href,omitempty"`
	// Unique identifier of the target specification
	Id string `json:"id,omitempty"`
	// Name of the target  characteristic
	Name string `json:"name,omitempty"`
	// Type of relationship such as aggregation, migration, substitution,
	RelationshipType string `json:"relationshipType,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
}
