/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductPrice struct {

	BaseType string `json:"@baseType,omitempty"`

	SchemaLocation string `json:"@schemaLocation,omitempty"`

	Type_ string `json:"@type,omitempty"`

	Description string `json:"description,omitempty"`

	Name string `json:"name,omitempty"`

	Price *Price `json:"price,omitempty"`

	PriceType string `json:"priceType,omitempty"`

	ProductOfferingPrice *ProductOfferingPrice `json:"productOfferingPrice,omitempty"`

	RecurringChargePeriod string `json:"recurringChargePeriod,omitempty"`

	UnitOfMeasure string `json:"unitOfMeasure,omitempty"`
}
