/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A set of numbers that specifies the lower and upper limits for a ProductOffering that can be procured as part of the related BundledProductOffering. Values can range from 0 to unbounded
type BundledProductOfferingOption struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`
	// Default number of produc offereings that should be procured as part of the related BundledProductOffering
	NumberRelOfferDefault int32 `json:"numberRelOfferDefault,omitempty"`
	// lower limit for a product offering that can be procured as part of the related BundledProductOffering
	NumberRelOfferLowerLimit int32 `json:"numberRelOfferLowerLimit,omitempty"`
	// upper limit for a product offering that can be procured as part of the related BundledProductOffering
	NumberRelOfferUpperLimit int32 `json:"numberRelOfferUpperLimit,omitempty"`
}
