/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A migration, substitution, dependency or exclusivity relationship between/among service specifications.
type Model struct {

	Id *TimePeriod `json:"id,omitempty"`
}
