/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A tax item is created for each tax rate and tax type used in the bill.
type TaxItem struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`

	TaxAmount *Money `json:"taxAmount,omitempty"`
	// Tax category
	TaxCategory string `json:"taxCategory"`
	// Applied rate of the tax
	TaxRate float32 `json:"taxRate"`
}
