/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ResourceCandidate reference: A resource candidate is an entity that makes a ResourceSpecification available to a catalog.
type ResourceCandidateRef struct {
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// The actual type of the target instance when needed for disambiguation.
	ReferredType string `json:"@referredType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`
	// When sub-classing, this defines the sub-class entity name
	Type_ string `json:"@type,omitempty"`
	// Reference of the resource candidate
	Href string `json:"href,omitempty"`
	// Unique identifier of the resource candidate
	Id string `json:"id"`
	// Name of the resource candidate
	Name string `json:"name,omitempty"`
	// Version of the resource candidate
	Version string `json:"version,omitempty"`
}
