/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A base / value business entity used to represent money
type Money struct {
	// Currency (ISO4217 norm uses 3 letters to define the currency)
	Unit string `json:"unit,omitempty"`
	// A positive floating point number
	Value float32 `json:"value,omitempty"`
}
