/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Resource specification reference: A Specification is a detailed description of a tangible or intangible object made available externally in the form of a Offering to customers or other parties playing a party role.
type ResourceSpecification struct {
	// Reference of the resource specification.
	Href string `json:"href,omitempty"`
	// Unique identifier of the resource specification.
	Id string `json:"id"`
	// Name of the requiredResourceSpecification.
	Name string `json:"name,omitempty"`
	// Resource specification version.
	Version string `json:"version,omitempty"`
}
