/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Signature struct {

	CartSignature string `json:"cartSignature,omitempty"`

	ContextSignature string `json:"contextSignature,omitempty"`
}
