/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductOfferingQualificationResponse struct {
	// the immediate base class type of this product offering
	BaseType string `json:"@baseType,omitempty"`
	// The class type of this Product offering
	Type_ string `json:"@type,omitempty"`

	Description string `json:"description,omitempty"`

	Id string `json:"id,omitempty"`

	ProvideAlternative bool `json:"provideAlternative,omitempty"`

	ProvideUnavailabilityReason bool `json:"provideUnavailabilityReason,omitempty"`

	QualificationResult string `json:"qualificationResult,omitempty"`

	ProductOfferingQualificationItemContainer []ProductOfferingQualificationResponseProductOfferingQualificationItemContainer `json:"productOfferingQualificationItemContainer&quot;,omitempty"`
}
