/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Price struct {

	BaseType string `json:"@baseType,omitempty"`

	SchemaLoaction string `json:"@schemaLoaction,omitempty"`

	Type_ string `json:"@type,omitempty"`

	ActionCardinality int32 `json:"actionCardinality,omitempty"`

	ChangeAmount *Money `json:"changeAmount,omitempty"`

	Discount *Money `json:"discount,omitempty"`

	DutyFreeAlteredAmount *Money `json:"dutyFreeAlteredAmount,omitempty"`

	DutyFreeAmount *Money `json:"dutyFreeAmount,omitempty"`

	Percentage float32 `json:"percentage,omitempty"`

	TaxIncludedAlteredAmount *Money `json:"taxIncludedAlteredAmount,omitempty"`

	TaxIncludedAmount *Money `json:"taxIncludedAmount,omitempty"`

	TaxRate float32 `json:"taxRate,omitempty"`
}
