/*
 * ProductOffering aggregation composite interface
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Account struct {

	BaseType string `json:"@baseType,omitempty"`

	ReferredType string `json:"@referredType,omitempty"`

	SchemaLocation string `json:"@schemaLocation,omitempty"`

	Type_ string `json:"@type,omitempty"`

	AccountType string `json:"accountType,omitempty"`

	Description string `json:"description,omitempty"`

	Href string `json:"href,omitempty"`

	Id string `json:"id,omitempty"`

	LastModified time.Time `json:"lastModified,omitempty"`

	Name string `json:"name,omitempty"`

	PaymentStatus string `json:"paymentStatus,omitempty"`

	State string `json:"state,omitempty"`
}
